### ISSUE TITLE
standard footer missing column container

### ISSUE THREAD

**Issue by thedannywahl** [eduridden/moodle-theme_elegance#12]
helplink and purge caches overflow the container because there is a row div, but no column div.
![screen shot 2014-02-25 at 12 54 27 pm](https://f.cloud.github.com/assets/743499/2254407/0307b1c4-9dd9-11e3-871b-dfea371ffe6c.png)

![screenshot_2014-02-25-10-05-25](https://f.cloud.github.com/assets/743499/2254409/06ea83f2-9dd9-11e3-8de2-aecff6879fd1.png)

**Comment by eduridden** [comment]
Fixed in master
