### ISSUE TITLE
sub-submenus don't appear

### ISSUE THREAD

**Issue by thedannywahl** [eduridden/moodle-theme_elegance#24]
even though they're rendered - sub-submenus don't appear on the theme:

Moodle community|https://moodle.org <--works
-Moodle free support|https://moodle.org/support <--works
-Moodle development|https://moodle.org/development <--works
--Moodle Docs|http://docs.moodle.org|Moodle Docs <--doesn't work
--German Moodle Docs|http://docs.moodle.org/de|Documentation in German|de
Moodle.com|http://moodle.com/ <--doesn't work

**Comment by ds125v** [comment]
Bootstrap 3 doesn't support submenus, more info here:

https://github.com/bmbrands/theme_bootstrap/issues/168

**Comment by eduridden** [comment]
As mentioned above. Bootstrap3 has dropped support for the sub menu's and I agree with their logic. 

I have updated the theme with an experimental CSS hack that should bring the submenu's back. Grab from the master branch if you want to try it out. Please create a new issue number to track issues with it.

**Comment by thedannywahl** [comment]
While I'm not saying this issue should be reopened - I'd like to suggest that it's still possible that we render all items inline.
-foo
--bar
becomes 
-foo
-bar
