### ISSUE TITLE
Interoperability with course formats.

### ISSUE THREAD

**Issue by gjb2048** [eduridden/moodle-theme_elegance#3]
Currently interoperability with contributed course formats is not working.  Please see https://moodle.org/mod/forum/discuss.php?d=251492#p1095519 and https://moodle.org/mod/forum/discuss.php?d=251492#p1095540.

Not really a request on you Julian to fix but a note in case I have a 'Mind that bus, what bus? Splat' incident.

**Comment by eduridden** [comment]
I will close this now as Gareth has released updted versions of his course formats
