### ISSUE TITLE
Font Awesome broken on 2014.imoot.org

### ISSUE THREAD

**Issue by ds125v** [eduridden/moodle-theme_elegance#31]
I just visited 2014.imoot.org and the fonts aren't working for me (on various browsers), it looks like the CSS might be pointing to the wrong directory.

**Comment by gjb2048** [comment]
This is because the CSS has the additional 'v=4.0.0' parameters in the URL
as seen in the file: http://2014.imoot.org/theme/elegance/style/elegance.css.
 The fonts are there: http://2014.imoot.org/theme/elegance/fonts/.

But there seems to be something odd going on too with the cache.

http://about.me/gjbarnard

**Comment by gjb2048** [comment]
Also when using the fontwww mechanism you need to add code to the pluginfile serving method too: https://github.com/gjb2048/moodle-theme_shoelace/blob/MOODLE_25/lib.php#L81 which matches https://github.com/gjb2048/moodle-theme_shoelace/blob/MOODLE_25/lib.php#L60.  But Elegance only has: https://github.com/moodleman/moodle-theme_elegance/blob/master/lib.php#L39 and not the serving code in: https://github.com/moodleman/moodle-theme_elegance/blob/master/lib.php#L325.

**Comment by gjb2048** [comment]
Alternatively, just use the new M2.6 font serving mechanism and tweak the FontAwesome CSS: https://github.com/gjb2048/moodle-theme_shoelace/blob/MOODLE_26/style/font-awesome.css#L7.

**Comment by ds125v** [comment]
The CSS looks like it's trying to get these fonts:

http://2014.imoot.org/filter/fontawesome/fonts/

but maybe aiming slight too high up the directory tree?

**Comment by gjb2048** [comment]
Also this URL is failing: http://2014.imoot.org/pluginfile.php/1/theme_elegance/fonts/1394084855/fontawesome-webfont.ttf?v=4.0.0 - so my theme issue logic is correct.

**Comment by gjb2048** [comment]
The filter URL looks odd: http://2014.imoot.org/theme/styles.php/elegance/filter/fontawesome/fonts/fontawesome-webfont.woff?v=4.0.1 as it's asking the theme!

**Comment by gjb2048** [comment]
Looks like the filter CSS is broken in terms of having no Moodle https etc. serving code: http://2014.imoot.org/filter/fontawesome/styles.css

**Comment by gjb2048** [comment]
But I thought that the filter did not supply the font but left it down to the theme as stated in 'Important note' on: https://moodle.org/plugins/view.php?plugin=filter_fontawesome.

**Comment by eduridden** [comment]
I have decided to really simplify this and remove the CDN option from this theme. Not really needed anyways. If a particular user really needs it they can add it easily enough themselves
