### ISSUE TITLE
How edit frontpage

### ISSUE THREAD

**Issue by johnfelipe** [eduridden/moodle-theme_elegance#32]
i need custom with:

![custom](https://f.cloud.github.com/assets/428820/2369845/16b0ba90-a7ed-11e3-9656-4a5378f1cde4.png)

**Comment by eduridden** [comment]
Sorry John. This is for reporting bugs only. If you want custom jobs best to contact me directly or through the moodle forums. Closing this as not a bug

**Comment by johnfelipe** [comment]
i send you mail, tnks
