### ISSUE TITLE
Suggested Feature - Click block title to show/hide it's content (for Mobile)

### ISSUE THREAD

**Issue by nadavkav** [eduridden/moodle-theme_elegance#33]
Hi Julian,

Please consider adding the following JS code to enable a nice feature - Clicking the block's title to hide/show it's content. (useful for mobile situations)

Just paste the following code into javascript/blocks.js

``` javascript
/* Clicking the Header of the block, hide/show the block's content
    Credit to Itamar Zadok (https://moodle.org/mod/forum/discuss.php?d=218799#p982036)
*/

YUI().use("node-base","node-event-simulate", function(Y) {
    var btn1_Click = function(e)
    {
        var targetBlock = e.target.ancestor('.block', true);

        // Don't run if in editing mode
        if (targetBlock.hasClass('block_with_controls')) {
            return false;
        }

        var hiderShow = targetBlock.one('.block-hider-show');
        var hiderHide = targetBlock.one('.block-hider-hide');

        // If propogating from simulation, halt
        if (e.target == hiderShow || e.target == hiderHide) {
            e.halt(true);
            return false;
        }

        if (targetBlock.hasClass('hidden')) {
            // Try show
            if (hiderShow) {
                hiderShow.simulate('click');
            }
        } else {
            // Try hide
            if (hiderHide) {
                hiderHide.simulate('click');
            }
        }
        return false;

    };
    Y.on("click", btn1_Click, ".header .title");
});
```

And add blocks to the config.php 

``` javascript
$THEME->javascripts_footer = array(
    'fitvid', 'blocks'
);
```

**Comment by eduridden** [comment]
How have I never seen that before? Absolutely! Consider it added.

**Comment by gjb2048** [comment]
Is this in core? And if not, why not!

**Comment by eduridden** [comment]
One important question. i want to disable this working in ONE region only (custom frontpage region) is there a way to do this? Will cause confusion otherwise

**Comment by nadavkav** [comment]
I guess you could add the classes that you wish to exclude it from working,
into the JS code...

if (targetBlock.hasClass('_do_not_work_within_this_class_')) {
            return false;
        }

**Comment by gjb2048** [comment]
I would have thought the JS to see if the id of the blocks parent (an 'aside' tag) is 'block-region-custom-frontpage' or what ever you have called it.  Check at top and if so return false.

**Comment by nadavkav** [comment]
Credit to Itamar Zadok

**Comment by eduridden** [comment]
I so need to learn to be a "proper" developer. JS always does my head in :)

**Comment by eduridden** [comment]
Added the following but it insists on still working! What have I missed.

// Don't use in front page custom region
        if (targetBlock.hasClass('block-region-side-middle')) {
            return false;
        }

Is it because his is a parent class I am checking?

**Comment by gjb2048** [comment]
You need the parent of targetBlock.

I am a proper developer and JS does my head in!

**Comment by eduridden** [comment]
OK. I am probably way of base here..but let me know what I am doing wrong as I reverse engineer this.

First i am checking for the parent region

var targetRegion = e.target.ancestor('.block-region', true);

I need to check if that region contains an ID, not a class. I know the following won't work. How do I update this to check for the div ID?

// Don't use in front page custom region
if (targetRegion.hasClass('block-region-side-middle')) {
return false;
}

**Comment by gjb2048** [comment]
Use 'one' and then test for 'null' - http://yuilibrary.com/yui/docs/node/ - at a guess:

var targetBlock = e.target.ancestor('.block', true);
var targetRegion = targetBlock.ancestor('.block-region', true);

var sideMiddle = targetRegion.one('#block-region-side-middle');

if (sideMiddle) return false;

May work, YUI is not my strong point.

**Comment by gjb2048** [comment]
But then this: http://yuilibrary.com/yui/docs/node/#node-properties seems to suggest that targetRegion.get('id') will get the id?

**Comment by gjb2048** [comment]
Looking at http://yuilibrary.com/yui/docs/event/#the-callback-and-the-event-object and http://yuilibrary.com/forum/viewtopic.php?p=23317 you can get the id with get('id').
