### ISSUE TITLE
homelink()

### ISSUE THREAD

**Issue by mcwe** [eduridden/moodle-theme_elegance#38]
Just wondering if it would be possible to add an additional setting to turn this off in the footer or change it from within the General Settings page in the Elegance theme.

**Comment by eduridden** [comment]
No. I do not intend to add a setting as this is standard in all moodle core themes and I would like it standard here. Users could always add custom css to the theme settings to remove this link however.

**Comment by mcwe** [comment]
Cool that is what I will do.
