### ISSUE TITLE
"Create new account" and "Lost password?" form buttons to full width?

### ISSUE THREAD

**Issue by mpuusaar** [eduridden/moodle-theme_elegance#39]
The "Create new account" and "Lost password?" buttons on the front page login block are currently distributed unevenly. What do you think about extending them to full width of the login block?

This can be simply achieved by altering the following CSS:
.block_login .content .footer div:nth-child(1) a {
background: green;
border: 1px solid #b4b4b7;
}

to

.block_login .content .footer div:nth-child(1) a {
background: green;
border: 1px solid #b4b4b7;
width: 100%;
}

The same has to be done with ".block_login .content .footer div:nth-child(2) a"

Current login block:
![elegance_login_current](https://f.cloud.github.com/assets/4007704/2395682/e6c89faa-a9cc-11e3-83dd-3eb2cc1fe7d6.PNG)

Suggested login block:
![elegance_login_suggestion](https://f.cloud.github.com/assets/4007704/2395683/e6c8a5e0-a9cc-11e3-84ed-ad19d5e7c44e.PNG)

**Comment by eduridden** [comment]
Thanks for this. I have gone with a slight variation but starting with your idea. Thanks again for the input
