### ISSUE TITLE
Colours and fonts of "Lost password?" button are different on front page and login page

### ISSUE THREAD

**Issue by mpuusaar** [eduridden/moodle-theme_elegance#40]
If the login block is being used on the front page then it is noticeable that the colour and font of the "Lost password?" button is different on the front page and on the login page.

Is this intentional? If not, then I would be happy to fix it :)
I would suggest using the red from login page also on front page.

Login block on front page:
![elegance_login_current](https://f.cloud.github.com/assets/4007704/2395818/205d09f2-a9cf-11e3-8e29-28da95f80a88.PNG)

Login block on login page:
![login_colours](https://f.cloud.github.com/assets/4007704/2395817/205714ca-a9cf-11e3-85c8-df3e97f64bf8.PNG)

**Comment by eduridden** [comment]
Thanks for the report. Colors now fixed

**Comment by mpuusaar** [comment]
Thanks for fixing the colors - they look much nicer now :).
There´s still an issue with the fonts on the front page login block (see the first screenshot I have attached). Can you reproduce this and fix it?
