### ISSUE TITLE
General Edit Section

### ISSUE THREAD

**Issue by mcwe** [eduridden/moodle-theme_elegance#42]
In the General Editing area the "Section Name" and "Summary" text box/field are out of  the content section of the page. Please see screen shot. (attached)

![screen shot 2014-03-12 at 2 00 31 pm](https://f.cloud.github.com/assets/6810607/2402942/b11747a6-aa28-11e3-9785-e166a7bf6ea9.png)

**Comment by eduridden** [comment]
Sadly currently i can do nothing to fix this. Moodle sets th size of those edit boxes and they cannot be overridden from a theme.

**Comment by mcwe** [comment]
Thanks.
