### ISSUE TITLE
Problem with site quick-links

### ISSUE THREAD

**Issue by mcolliver** [eduridden/moodle-theme_elegance#43]
If you change the amount of site quick-links should the code generated for the grid layout reflect the number of links picked?

I have set up my site for three links but think the spacing look better if the code uses something like col-lg-4 (so 12 split equally?).

Currently it is just hardcoded as follows:

```
echo '<div class="col-lg-2 col-md-3 col-sm-4 col-xs-6" id="quicklink">';
```

I might be wrong but should the numbers used above change to reflect the amount of site links?

**Comment by eduridden** [comment]
we cant change the numbers for every individual number of combinations. They curently do adapt based on resolution. This is something I dont intend to change at this time unless I can be persuaded with a good reason

**Comment by mcolliver** [comment]
Fair enough - I have implemented this and it seems to work quite nicely:

```
//make use of $quicklinksnum for better behaviour       
// set lg size to be 12/$quicklinksnum if $quicklinksnum is less than 4
// so with 1 link you get lg-12, 2 links you get lg-6, 3 links you get lg-4 and 4+ links you get lg-3 
// set md size to be 12/$quicklinksnum if $quicklinsnum is less than 3
$lg = ( $quicklinksnum <4 ? 12/$quicklinksnum : 3 );
$md = ( $quicklinksnum <3 ? 12/$quicklinksnum : 4 );
echo "<div class='col-lg-$lg col-md-$md col-sm-4 col-xs-6' id='quicklink'>";
```

**Comment by eduridden** [comment]
Ill try it out. Im not "anti" the idea, just worried about someone winging about how 5 looks, or 7. Cant keep everyone happy :)
