### ISSUE TITLE
RE: Logo Issue

### ISSUE THREAD

**Issue by mcwe** [eduridden/moodle-theme_elegance#46]
Hi,

After upgrading to v 2.6.2 the Logo in the upper left hand corner appears to be calling the  Short name for the site instead of the logo image in the logo setting area under the elegance theme. What is strange is when I am on the log in page the image appears correctly. (See attachment(s))

Image of logo area using short name: (Through out the site logged in or not logged in)
![screen shot 2014-03-17 at 10 11 47 am](https://f.cloud.github.com/assets/6810607/2438863/d988b0fe-adf6-11e3-83e1-2922585d9ed4.png)

Image of logo area in the login area:
![screen shot 2014-03-17 at 10 16 11 am](https://f.cloud.github.com/assets/6810607/2438915/74d6ad7c-adf7-11e3-8932-457e88e70d01.png)

Is there any recommended fixes for this?

**Comment by eduridden** [comment]
My fault. Missed using custom logo code after an upgrade. Now rectified in Master

**Comment by mcwe** [comment]
Cool thanks!
