### ISSUE TITLE
RE: Moodle logo bottom of Site Page 

### ISSUE THREAD

**Issue by mcwe** [eduridden/moodle-theme_elegance#47]
Hi,

Regarding the moodle logo at the bottom of the page. I had an issue trying to get it to rendering properly on a colored background. I had to go in and hard code in the lib/outputrenderers.php, which I would like to avoid if possible. 

The issue stems form the .sitelink vs the .homelink. For some reason the .sitelink looks horrible.

See the code below:

![screen shot 2014-03-17 at 10 59 11 am](https://f.cloud.github.com/assets/6810607/2439500/7398784a-adfd-11e3-8b38-6a7462a839b7.png)

**Comment by eduridden** [comment]
I have added css fix to master

**Comment by mcwe** [comment]
Sweet.
