### ISSUE TITLE
RE: Slide show

### ISSUE THREAD

**Issue by mcwe** [eduridden/moodle-theme_elegance#48]
Hi,

I was wondering if it would be possible to have the slide show responsive to the widening of the browser? Currently if you stretch the window to the right the image stops while the rest of the site follows suite. (See attached)

![screen shot 2014-03-18 at 7 40 14 am](https://f.cloud.github.com/assets/6810607/2449320/0725e8ec-aeb0-11e3-8fc8-aa2ec442b5ae.png)

Thanks!

**Comment by eduridden** [comment]
To be honest I would have no idea how to code that. It appears to be a limitation of the unslider code. Obviosly if you hit refresh its fine, but it does not auto refresh after a resize.
