### ISSUE TITLE
Please credit my work on your theme Elegance

### ISSUE THREAD

**Issue by ghost** [eduridden/moodle-theme_elegance#60]
Just left a note on Moodle.org. Thought I would post here too.

I'm Aaron Marr from Educational Technology at Falmouth University, UK. I can see you are using our theme 'Learning Space' as a base for your theme 'Elegance.' I would very much appreciate credit, where it is due, for the design work I have done – work that you appear to be using without reference.

Best Regards,
Aaron Marr.
Falmouth University.

**Comment by DBezemer** [comment]
Aaron, I cannot speak for Julian, but I do not see any references to anything but original work. The theme is based on the BootStrap3 theme that Bas Brands created, and the options are derived from Julian's theme "Essential".

If http://learningspace.falmouth.ac.uk/ is the theme you reference with your claim, I would like to invite everyone to compare, and see for themselves.

If you are making accusations like this please back them with proof, indications of proof or references to your original work.

**Comment by ghost** [comment]
Hi DBezemer,

I'll wait for a response from Julien. I have plenty of proof, which I'll provide if need be. I would prefer a constructive conversation about intellectual property within open source.

**Comment by mpuusaar** [comment]
Dear Aaron,

I can understand that this is personal for you but as you already pointed out, you would like to have a conversation about intellectual property within open source and this also means that others could join in on the conversation ;)
Our organization is just implementing Elegance to be the main theme for a Moodle site with over 125 000 users and your accusations are really causing worries about the legal aspects of the theme we have chosen.
As the people watching this project are apparently really interested and exited about the Elegance theme, I would ask you to explain your logic and accusations.

Thanks for your time on helping to understand the problem.

**Comment by DBezemer** [comment]
Looking at the initial commit this was a clean bootstrap3 theme (https://github.com/moodleman/moodle-theme_elegance/commit/f167a54e48e58034c20283f947b9f23b9b279129) this commit was 4 months ago, prior to the creation of your own code at https://github.com/aaronmarruk/LearningspaceTheme which is only 2 months ago. I also do not see any images that could have been "stolen" from your theme, as this theme uses various freely available images like halflings, bootstrap icons, bootstrap images and other open available resources.

If you are making this kind of serious accusations, back them up with evidence. Show the original works (links) and show how they have been copied by Julian. The way it seems now is that you are trying to take partial credit for work done by Julian, which in my book is "not cool".

**Comment by ghost** [comment]
I have now had a response from moodleman and all discussions are happening here:
https://github.com/moodleman/moodle-theme_elegance/issues/62#issuecomment-39531824

**Comment by ghost** [comment]
Credit has now been given in the README here: https://github.com/moodleman/moodle-theme_elegance
