### ISSUE TITLE
Error in process_user_messages() function

### ISSUE THREAD

**Issue by nadavkav** [eduridden/moodle-theme_elegance#74]
Undefined variable $usermessages
https://github.com/moodleman/moodle-theme_elegance/blob/master/renderers/core_renderer.php#L276

protected function process_user_messages() {
        $messagelist = array();
        foreach ($usermessages as $message) {

**Comment by gjb2048** [comment]
Julian no longer maintains the theme, please raise an issue here: https://github.com/thedannywahl/moodle-theme_elegance/issues

**Comment by nadavkav** [comment]
Thanks Gareth, I see you already fixed it :smile:

**Comment by gjb2048** [comment]
Oh crumbs!  So I did :)
