### ISSUE TITLE
Autofocus Login Form Option

### ISSUE THREAD

**Issue by Panman82** [eduridden/moodle-theme_elegance#75]
The theme does not abide by the Moodle configuration option "Autofocus login page form" under Site Admin > Plugins > Authentication > Manage authentication. (Yeah, odd place for that option.) So if the login form is displayed, an "autofocus" attribute should be applied to the username input/field.

**Comment by gjb2048** [comment]
Julian no longer maintains the theme, please raise an issue here: https://github.com/thedannywahl/moodle-theme_elegance/issues

**Comment by Panman82** [comment]
Done. Thanks 

https://github.com/thedannywahl/moodle-theme_elegance/issues/72
