### ISSUE TITLE
Menu button does not work (Galaxy Note II + latest Moodle 2.7dev)

### ISSUE THREAD

**Issue by nadavkav** [eduridden/moodle-theme_elegance#8]
The "three lines" menu button does not open up.

I am using latest Elegance (2014022002) with latest Moodle 2.7dev (2014021300)
on Galaxy Note II + Chrome 33 beta.

Using Chrome developer emulation mode from my development laptop, I get the same issue.

BTW, Using latest Essential, the button works fine. (on the real device and on the Chrome emulation mode)

**Comment by thedannywahl** [comment]
![screenshot_2014-02-25-10-04-29](https://f.cloud.github.com/assets/743499/2254374/07de8020-9dd8-11e3-82f1-85f7168a72ef.png)
here's a picture of the menu activated on my Samsung Galaxy Nexus - you can see it does nothing.

**Comment by nadavkav** [comment]
Just updated. 11/3/2014. Still an issue.
With a very (very) quick look into the code... disabling/commenting:
@media (max-width: 979px)
.navbar .nav {
/\* display: none; */
}
solve this issue.

**Comment by eduridden** [comment]
Grr...Can't believe I missed that! Fixed and committed yo github. Thanks for sharing

**Comment by nadavkav** [comment]
Bless you dear Julian!
(btw, I am about to send you a batch of RTL fixes, so.... get ready :wink: )

**Comment by nadavkav** [comment]
I can not hold myself...
What a beautiful theme !!!

**Comment by eduridden** [comment]
Hit me. If you can send them ASAP as I want to release a point release update for this theme today with a slew of current fixes
