### ISSUE TITLE
Social Networking Links don't work

### ISSUE THREAD

**Issue by thedannywahl** [eduridden/moodle-theme_elegance#9]
it seems that the social networking links are using JavaScript to change the document location - unfortunately this isn't working on Mac OS X w/ Firefox, or Android with Google Chrome.  Here's a screenshot of the "active" link but it's not doing anything:
![screenshot_2014-02-25-10-05-08](https://f.cloud.github.com/assets/743499/2254389/719d28f4-9dd8-11e3-962c-b378d142a297.png)

**Comment by mcwe** [comment]
Here is an example of proposed change:
<button type="button" ONCLICK="window.open(\''.$haswebsite.'\')" class="socialicon website">

Also the twitter class is wrong. It is currently twiiter and not twitter and need to be changed

It needs to be changed in /themes/elegance/layout/includes/footer.php

**Comment by eduridden** [comment]
This should now be updated in master
